In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [6]:
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [7]:
a1 = np.array(l1)

In [8]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [9]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [11]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.size

7

In [18]:
a2.size

6

In [19]:
a3.size

9

In [20]:
a1.shape

(7,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(1, 3, 3)

In [23]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
np.random.randint(2,50 ,(3,4) )

array([[47, 42, 14, 10],
       [20, 44, 20, 47],
       [39, 36,  2, 42]])

In [28]:
np.random.randint(2,50 ,(2,3,4) )

array([[[49, 31, 34,  6],
        [15, 17, 45, 25],
        [34, 48, 27, 48]],

       [[33, 37, 14, 25],
        [31, 13, 12, 18],
        [ 3, 22, 15, 47]]])

In [30]:
np.random.rand(5,4)

array([[0.80604956, 0.5048267 , 0.18358572, 0.62658634],
       [0.43150151, 0.44692823, 0.46249923, 0.85274558],
       [0.61764072, 0.99963842, 0.25822707, 0.48867623],
       [0.68581434, 0.91466469, 0.58587992, 0.5755879 ],
       [0.44601198, 0.34775366, 0.0298422 , 0.08339031]])

In [31]:
a4 =  np.random.randn(4,4)

In [35]:
a4

array([[-1.11367762,  1.32180372, -0.73624026,  0.36157888],
       [ 1.24287212,  1.71127692,  0.20833801, -0.56874626],
       [ 0.64846819,  1.388291  , -0.24136824, -0.56597993],
       [ 0.14512458, -1.08610265,  0.27075865,  1.64604596]])

In [36]:
a4.reshape(2,8)

array([[-1.11367762,  1.32180372, -0.73624026,  0.36157888,  1.24287212,
         1.71127692,  0.20833801, -0.56874626],
       [ 0.64846819,  1.388291  , -0.24136824, -0.56597993,  0.14512458,
        -1.08610265,  0.27075865,  1.64604596]])

In [37]:
a4.reshape(8,2)

array([[-1.11367762,  1.32180372],
       [-0.73624026,  0.36157888],
       [ 1.24287212,  1.71127692],
       [ 0.20833801, -0.56874626],
       [ 0.64846819,  1.388291  ],
       [-0.24136824, -0.56597993],
       [ 0.14512458, -1.08610265],
       [ 0.27075865,  1.64604596]])

In [38]:
a4.reshape(16,1)

array([[-1.11367762],
       [ 1.32180372],
       [-0.73624026],
       [ 0.36157888],
       [ 1.24287212],
       [ 1.71127692],
       [ 0.20833801],
       [-0.56874626],
       [ 0.64846819],
       [ 1.388291  ],
       [-0.24136824],
       [-0.56597993],
       [ 0.14512458],
       [-1.08610265],
       [ 0.27075865],
       [ 1.64604596]])

In [39]:
a4.reshape(2,-134564364)

array([[-1.11367762,  1.32180372, -0.73624026,  0.36157888,  1.24287212,
         1.71127692,  0.20833801, -0.56874626],
       [ 0.64846819,  1.388291  , -0.24136824, -0.56597993,  0.14512458,
        -1.08610265,  0.27075865,  1.64604596]])

In [40]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-1.11367762,  1.32180372, -0.73624026,
                 0.36157888],
               [ 1.24287212,  1.71127692,  0.20833801,
                -0.56874626]],

              [[ 0.64846819,  1.388291  , -0.24136824,
                -0.56597993],
               [ 0.14512458, -1.08610265,  0.27075865,
                 1.64604596]]]]]]]]]])

In [41]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [42]:
a1[0]

'4'

In [43]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [44]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [45]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [46]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [48]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [49]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [50]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [51]:
a5 = np.random.randint(2,90 , (6,5))

In [52]:
a5

array([[46, 31, 77, 71, 33],
       [55, 84, 23, 38, 14],
       [55, 31,  7, 35, 56],
       [18, 39, 32, 66, 47],
       [60, 57, 52, 57,  9],
       [46, 33, 52, 50, 26]])

In [53]:
a5[a5>40]

array([46, 77, 71, 55, 84, 55, 56, 66, 47, 60, 57, 52, 57, 46, 52, 50])

In [54]:
a5

array([[46, 31, 77, 71, 33],
       [55, 84, 23, 38, 14],
       [55, 31,  7, 35, 56],
       [18, 39, 32, 66, 47],
       [60, 57, 52, 57,  9],
       [46, 33, 52, 50, 26]])

In [56]:
a5[0,1] = 100

In [57]:
a5

array([[ 46, 100,  77,  71,  33],
       [ 55,  84,  23,  38,  14],
       [ 55,  31,   7,  35,  56],
       [ 18,  39,  32,  66,  47],
       [ 60,  57,  52,  57,   9],
       [ 46,  33,  52,  50,  26]])

In [58]:
a6 = np.random.randint(0,3 , (3,3))

In [59]:
a7 = np.random.randint(0,3 , (3,3))

In [60]:
a6

array([[2, 2, 0],
       [2, 0, 1],
       [0, 0, 0]])

In [62]:
a7



array([[1, 0, 1],
       [0, 0, 2],
       [2, 1, 1]])

In [63]:
a6*a7

array([[2, 0, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [64]:
a6@a7

array([[2, 0, 6],
       [4, 1, 3],
       [0, 0, 0]])

In [65]:
a6

array([[2, 2, 0],
       [2, 0, 1],
       [0, 0, 0]])

In [66]:
a6+100

array([[102, 102, 100],
       [102, 100, 101],
       [100, 100, 100]])

In [67]:
a6*2

array([[4, 4, 0],
       [4, 0, 2],
       [0, 0, 0]])

In [68]:
a6/0

C:\Users\use\AppData\Local\Temp\ipykernel_9172\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\use\AppData\Local\Temp\ipykernel_9172\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [inf, nan, inf],
       [nan, nan, nan]])

In [97]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [98]:
a6**3


array([[0, 1, 0],
       [0, 1, 8],
       [0, 0, 1]], dtype=int32)

In [73]:
a8 = np.zeros((4,4))

In [74]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
a9  = np.ones((4,5))

In [76]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [78]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [79]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [81]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [114]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [83]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [84]:
a6.T

array([[2, 2, 0],
       [2, 0, 0],
       [0, 1, 0]])

In [85]:
a6

array([[2, 2, 0],
       [2, 0, 1],
       [0, 0, 0]])

In [86]:
a5

array([[ 46, 100,  77,  71,  33],
       [ 55,  84,  23,  38,  14],
       [ 55,  31,   7,  35,  56],
       [ 18,  39,  32,  66,  47],
       [ 60,  57,  52,  57,   9],
       [ 46,  33,  52,  50,  26]])

In [87]:
np.sqrt(a5)

array([[ 6.78232998, 10.        ,  8.77496439,  8.42614977,  5.74456265],
       [ 7.41619849,  9.16515139,  4.79583152,  6.164414  ,  3.74165739],
       [ 7.41619849,  5.56776436,  2.64575131,  5.91607978,  7.48331477],
       [ 4.24264069,  6.244998  ,  5.65685425,  8.1240384 ,  6.8556546 ],
       [ 7.74596669,  7.54983444,  7.21110255,  7.54983444,  3.        ],
       [ 6.78232998,  5.74456265,  7.21110255,  7.07106781,  5.09901951]])

In [122]:
np.exp(a5)

array([[6.39843494e+17, 2.68811714e+43, 1.95729609e+11, 7.49841700e+33,
        5.05239363e+31],
       [3.10429794e+26, 1.25236317e+29, 1.06864746e+13, 5.45981500e+01,
        2.75851345e+33],
       [4.85165195e+08, 3.49342711e+19, 6.07603023e+37, 4.03428793e+02,
        1.50609731e+35],
       [4.03428793e+02, 6.23514908e+27, 1.31881573e+09, 1.73927494e+18,
        1.40934908e+22],
       [3.10429794e+26, 2.98095799e+03, 1.44625706e+12, 1.31881573e+09,
        7.69478527e+23],
       [4.31123155e+15, 1.40934908e+22, 8.43835667e+26, 4.60718663e+28,
        9.74480345e+09]])

In [88]:
np.log10(a5)

array([[1.66275783, 2.        , 1.88649073, 1.85125835, 1.51851394],
       [1.74036269, 1.92427929, 1.36172784, 1.5797836 , 1.14612804],
       [1.74036269, 1.49136169, 0.84509804, 1.54406804, 1.74818803],
       [1.25527251, 1.59106461, 1.50514998, 1.81954394, 1.67209786],
       [1.77815125, 1.75587486, 1.71600334, 1.75587486, 0.95424251],
       [1.66275783, 1.51851394, 1.71600334, 1.69897   , 1.41497335]])

In [89]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [90]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [92]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [93]:
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [94]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])